### ISSUE TITLE
Server.exe shows the same warning every time and can´t connect using loader

### ISSUE THREAD

**Issue by cesaredr** [TLeonardUK/ds3os#25] opened 2021-11-17 05:13 UTC
2021-11-16 23:08:41 │ Success │ Server is now running.
2021-11-16 23:08:43 │ Warning │ Recieved error when trying to advertise server on master server. Response was not valid json.
2021-11-16 23:10:46 │ Warning │ Recieved error when trying to advertise server on master server. Response was not valid json.
2021-11-16 23:11:08 │ Log     │ [Login Service{25.4.241.91:38345}] Client connected.
2021-11-16 23:11:09 │ Log     │ [Login Service{25.4.241.91:38345}] Client disconnected.

**Comment by TLeonardUK** [comment] 2021-11-17 09:47
Duplicate of https://github.com/TLeonardUK/ds3os/issues/18

This just means the master server is down at the moment, I don't currently have it running in a permanent place. You can still connect via the loader by importing the ds3osconfig files the server creates.

**Closed by TLeonardUK** 2021-11-17 09:47 UTC

**Comment by cesaredr** [comment] 2021-11-18 15:57
thanks :)
